name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
      - run: julia -e "use Pkg; Pkg.add(url='https://github.com/Qaintum/Qaintessent.jl'); Pkg.add(url='https://github.com/Qaintum/Qaintmodels.jl');"
      - uses: julia-actions/julia-runtest@master
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1


