name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.5.0
<<<<<<< HEAD
      - run: julia --project test/installQaintessent.jl
      - uses: julia-actions/julia-runtest@master
=======
      - uses: julia-actions/julia-runtest@master
>>>>>>> origin/master
