name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: julia --project test/installQaintessent.jl
      - uses: julia-actions/julia-runtest@master
