name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-runtest@master
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1


